### ISSUE TITLE
CoreProtect logging doesn't work

### ISSUE THREAD

**Issue by Dakotaa** [BG-Software-LLC/WildBuster#12]
### Minecraft's Version

1.16.5 Purpur-1151

### Plugin's Version

2.5.3

### Describe the bug

Blocks broken by chunk busters are not being logged in core protect. ("_No data found_" when inspecting blocks broken by a buster)

### To Reproduce

Have CoreProtect installed, use a chunk buster. No broken blocks will be logged.

### Additional Information

Using the latest version of CoreProtect (v20.3)

**Comment by OmerBenGera** [comment]
Weird. I will check it out, as it should work.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
