### ISSUE TITLE
NullPointerException Error with WorldGuard Hook

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/WildBuster#13]
### Minecraft's Version

BeerSpigot Premium and 1.8.8

### Plugin's Version

WildBuster-2.6.0-b38.jar

### Describe the bug

On server startup, I see an error NullPointerException about a world guard hook.

### To Reproduce

Load up a server with WildBuster-2.6.0-b38.jar and worldguard-6.2.jar, I'm unsure exactly how to reproduce the error but it shows up in the console.

### Additional Information

Here is the error: https://pastebin.com/UefzDWLL

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
