### ISSUE TITLE
Skulk Sensors console spam

### ISSUE THREAD

**Issue by RTCFlyer** [BG-Software-LLC/WildBuster#14]
### Minecraft's Version

1.18

### Plugin's Version

Latest

### Describe the bug

When using a wildbuster with skulk sensors within the chunk, the console will output an invalid ticking entity warning. 

### To Reproduce

Use a wild buster in a radius that contains a skulk sensor. 

### Additional Information

`[08:05:23 WARN]: Block entity minecraft:sculk_sensor @ BlockPosition{x=-1776, y=248, z=10336} state Block{minecraft:air} invalid for ticking:`

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
