### ISSUE TITLE
Unlimited Buster via OFFHAND

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildBuster#16]
### Minecraft's Version

1.16.5 PaperSpigot

### Plugin's Version

WildBuster-2.5.4-b34

### Describe the bug

Put buster in your offhand then place it, it won't run out.

### To Reproduce

Put buster in your offhand then place it, it won't run out.

### Additional Information

Video:
https://www.youtube.com/watch?v=bAwydfU20TE

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
