### ISSUE TITLE
Breaking a block when chunkbuster is in hand

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildBuster#18]
### Minecraft's Version

1.17.1 Paper

### Plugin's Version

Wildbuster 2.6.0-b41

### Describe the bug

Breaking a block (EX: Dirt) with the chunkbuster on your mainhand makes chunkbuster useless / not working.
also what's worst if there's like multiple chunk busters in your hand and you reproduce this bug, it makes ALL the buster in your main hand not functional.

EX: You do this bug with 32 chunk busters in your hand, all of them will be useless.

### To Reproduce

Hold chunkbuster in your mainhand, destroy a block EX: Dirt, place the chunk buster, it wont work anymore, see here on video below. 

### Additional Information

https://streamable.com/vv628l

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
Does it happen for you on another server with only WildBuster installed?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by illudota** [comment]
> Any news regarding this?

Installeed on 1.8.9 solo plugin, doesnt seem to happen, must be plugin conflict, ill report when it happens again, i resetted my server

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> Installeed on 1.8.9 solo plugin, doesnt seem to happen, must be plugin conflict, ill report when it happens again, i resetted my server

Find the conflicted plugin and report it to them :)
I am closing this for now
