### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by MythicGhoul** [BG-Software-LLC/WildBuster#19]
### Minecraft's Version

Latest version

### Plugin's Version

Latest verson

### Describe the bug

Using plots squared and players are able to break other players plots with the buster, didn't know if you could add support so it only breaks blocks within a players own claim and not the road

### To Reproduce

Use the buster on a plot work

### Additional Information

You suggested I open this ticket aha

**Comment by OmerBenGera** [comment]
Added in latest dev build.
