### ISSUE TITLE
Starting Level Issue

### ISSUE THREAD

**Issue by FaytalReplay** [BG-Software-LLC/WildBuster#23]
### Minecraft's Version

Pufferfish 1.19.2 (Paper fork)

### Plugin's Version

I've tested the latest stable version 2022.7 and the latest dev build #59 and the issue persists on both. I've also tested both versions on standalone servers with no other plugins installed.

### Describe the bug

Even though I set starting level to -1 it starts at the height of the highest block. So if I place the buster at 52 it will start busting the chunk at whatever height the highest block in the chunk is

### To Reproduce

Set the starting level to -1 and the issue should replicate

### Additional Information

Only thing I can think of is that this plugin might have been designed before the lowest world height went down to y-64 so now that y levels go negative, in newer versions it's messing with the code when you set y-1 because that's an actual block height now. Not sure though.

Config file: https://pastebin.com/1QhB5fKT

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
