### ISSUE TITLE
Not working on WineSpigot

### ISSUE THREAD

**Issue by illudota** [BG-Software-LLC/WildBuster#24]
### Minecraft's Version

WineSpigot Paper Fork 1.8.8

### Plugin's Version

v2022.7

### Describe the bug

Itt wont run and it runs error on console

### To Reproduce

Use winespigot

### Additional Information

https://mcpaste.io/2b10e4004e302b4c

**Comment by OmerBenGera** [comment]
Contact them regarding this as this is not an issue with WildBuster.
They edited something in the code of the CraftChunk#getChunkSnapshot that causes this to occur.
