### ISSUE TITLE
Buster not busting above y=255

### ISSUE THREAD

**Issue by Eccys** [BG-Software-LLC/WildBuster#29]
### Minecraft's Version

Purpur 1.19.4

### Plugin's Version

2023.3

### Describe the bug

Not busting above y=255

### To Reproduce

Initiate a 1.18.x+ minecraft server instance. Configure WildBuster to bust from y=319 as the max height. Place the chunk buster.

It will only bust from 255 and lower.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
