### ISSUE TITLE
wont chunk bust to 320

### ISSUE THREAD

**Issue by B3Scar3d** [BG-Software-LLC/WildBuster#30]
### Minecraft's Version

1.20+

### Plugin's Version

dev build 12 

### Describe the bug

will not bust to y 320, stops at y 254 even tho config is set at y 320 and y -63

### To Reproduce

tbh i dont know, i just know changing the config to y320 then reloading the plugin and then placing a chunk buster it only stops at 254

**Comment by OmerBenGera** [comment]
Duplicate of #29
